import { useState, useEffect, useCallback } from 'react'
import { Link } from 'react-router-dom'
import api from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { DataTable } from '@/components/ui/data-table'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Plus, ChevronLeft, ChevronRight, Eye, Printer } from 'lucide-react'
import { formatDate } from '@/lib/utils'

interface ClassOption {
  _id: string
  name: string
}

interface HomeworkItem {
  _id: string
  title: string
  description: string
  dueDate: string
  class: { _id: string; name: string }
  subject: { _id: string; name: string }
  teacher: { _id: string; name: string }
  submissionCount: number
  totalStudents: number
}

export default function HomeworkList() {
  const [classes, setClasses] = useState<ClassOption[]>([])
  const [selectedClass, setSelectedClass] = useState('all')
  const [homework, setHomework] = useState<HomeworkItem[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [page, setPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)

  useEffect(() => {
    fetchClasses()
  }, [])

  const fetchClasses = async () => {
    try {
      const { data } = await api.get('/classes')
      if (data.success) setClasses(data.data || [])
    } catch (err) {
      console.error('Failed to fetch classes:', err)
    }
  }

  const fetchHomework = useCallback(async () => {
    setIsLoading(true)
    try {
      const params: any = { page, limit: 20 }
      if (selectedClass !== 'all') params.class = selectedClass
      const { data } = await api.get('/homework', { params })
      if (data.success) {
        setHomework(data.data.homework || data.data || [])
        setTotalPages(data.data.totalPages || 1)
      }
    } catch (err) {
      console.error('Failed to fetch homework:', err)
    } finally {
      setIsLoading(false)
    }
  }, [selectedClass, page])

  useEffect(() => {
    fetchHomework()
  }, [fetchHomework])

  const handlePrint = (item: HomeworkItem) => {
    const logoUrl = `${window.location.origin}/icons/logo.jpeg`
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(`
      <html><head><title>Homework - ${item.title}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 36px; max-width: 680px; margin: auto; }
        .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #1e3a5f; padding-bottom: 14px; margin-bottom: 22px; }
        .header .brand { display: flex; align-items: center; gap: 12px; }
        .header img { width: 52px; height: 52px; border-radius: 12px; object-fit: cover; }
        .header h1 { margin: 0; font-size: 20px; color: #1e3a5f; }
        .header .sub { color: #666; font-size: 12px; margin-top: 3px; }
        .meta { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 16px; margin-bottom: 18px; font-size: 13px; }
        .meta table { width: 100%; border-collapse: collapse; }
        .meta td { padding: 4px 8px; }
        .meta td.k { color: #6b7280; font-weight: 600; width: 40%; }
        .desc { font-size: 14px; color: #1f2937; line-height: 1.7; }
        .due { margin-top: 22px; padding: 12px 16px; background: #fff7ed; border: 1px solid #fed7aa; border-radius: 8px; color: #9a3412; font-size: 14px; font-weight: 600; }
        .footer { text-align: center; color: #999; font-size: 11px; margin-top: 28px; padding-top: 12px; border-top: 1px solid #eee; }
        @media print { body { padding: 16px; } }
      </style></head><body>
        <div class="header">
          <div class="brand">
            <img src="${logoUrl}" alt="Leadership Study System Logo" />
            <div>
              <h1>Leadership Study System</h1>
              <div class="sub">Homework Assignment</div>
            </div>
          </div>
        </div>
        <div class="meta">
          <table>
            <tr><td class="k">Title</td><td><strong>${item.title}</strong></td></tr>
            <tr><td class="k">Class</td><td>${item.class?.name || '-'}</td></tr>
            <tr><td class="k">Subject</td><td>${item.subject?.name || '-'}</td></tr>
            <tr><td class="k">Teacher</td><td>${item.teacher?.name || '-'}</td></tr>
          </table>
        </div>
        <div class="desc">${item.description || 'No description provided.'}</div>
        <div class="due">Due Date: ${formatDate(item.dueDate)}</div>
        <div class="footer">Generated by Leadership Study System &mdash; ${new Date().toLocaleDateString('en-PK')}</div>
        <script>window.print()</script>
      </body></html>
    `)
    w.document.close()
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Homework</h1>
        <Link to="/admin/homework/create">
          <Button>
            <Plus className="h-4 w-4 mr-2" /> Create Homework
          </Button>
        </Link>
      </div>

      <div className="w-48">
        <Select value={selectedClass} onValueChange={(v) => { setSelectedClass(v); setPage(1) }}>
          <SelectTrigger><SelectValue placeholder="All Classes" /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Classes</SelectItem>
            {classes.map((c) => (
              <SelectItem key={c._id} value={c._id}>{c.name}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <DataTable
        columns={[
          { key: 'title', header: 'Title' },
          {
            key: 'class',
            header: 'Class',
            render: (row: HomeworkItem) => row.class?.name || '-',
          },
          {
            key: 'teacher',
            header: 'Teacher',
            render: (row: HomeworkItem) => row.teacher?.name || '-',
          },
          {
            key: 'dueDate',
            header: 'Due Date',
            render: (row: HomeworkItem) => {
              const isOverdue = new Date(row.dueDate) < new Date()
              return (
                <span className={isOverdue ? 'text-red-600' : ''}>
                  {formatDate(row.dueDate)}
                  {isOverdue && <Badge variant="destructive" className="ml-2 text-xs">Overdue</Badge>}
                </span>
              )
            },
          },
          {
            key: 'submissions',
            header: 'Submissions',
            render: (row: HomeworkItem) => (
              <span>{row.submissionCount || 0}/{row.totalStudents || 0}</span>
            ),
          },
          {
            key: 'actions',
            header: '',
            render: (row: HomeworkItem) => (
              <div className="flex items-center gap-1">
                <Button variant="ghost" size="sm" onClick={() => handlePrint(row)}>
                  <Printer className="h-4 w-4 mr-1" /> Print
                </Button>
                <Link to={`/admin/homework/${row._id}/submissions`}>
                  <Button variant="ghost" size="sm">
                    <Eye className="h-4 w-4 mr-1" /> Submissions
                  </Button>
                </Link>
              </div>
            ),
          },
        ]}
        data={homework}
        isLoading={isLoading}
        emptyMessage="No homework found"
      />

      {totalPages > 1 && (
        <div className="flex items-center justify-between">
          <p className="text-sm text-muted-foreground">Page {page} of {totalPages}</p>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage((p) => Math.max(1, p - 1))}>
              <ChevronLeft className="h-4 w-4" /> Prev
            </Button>
            <Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)}>
              Next <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      )}
    </div>
  )
}
